query GetTourActivities ($id: ID!) {
  __typename
  getTour(id: $id) {
    id
    description
    end_date
    isPublic
    name
    start_date
    activities (limit: 10) {
      items {
        id
        elapsed_time
        moving_time
        name
        start_date_local
        summary_polyline
        type
        strava_id
      }
      nextToken
    }
  }
  listAuths {
    items {
      id
      token_type
      strava_scope
      refresh_token
      expires_at
      access_token
    }
  }
}