
query GetActivities ($id: ID!, $nextToken: String) {
    getTour(id: $id) {
      id
      isPublic
      activities(limit: 50, nextToken: $nextToken) {
        items {
          id
          name
          distance
          elapsed_time
          moving_time
          start_latlng
          start_date_local
          summary_polyline
          type
          strava_id
        }
        nextToken
      } 
    }
  }