
query GetActivities ($id: ID!, $nextToken: String) {
    getTour(id: $id) {
      id
      description
      end_date
      isPublic
      name
      start_date
      __typename
      activities(limit: 50, nextToken: $nextToken) {
        items {
          id
          name
          distance
          elapsed_time
          moving_time
          start_latlng
          start_date_local
          summary_polyline
          type
          strava_id
          average_speed
          total_elevation_gain
          __typename
        }
        nextToken
      } 
    }
  }