query ListAuths(
  $filter: ModelAuthFilterInput
  $limit: Int
  $nextToken: String
) {
  listAuths(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      access_token
      expires_at
      refresh_token
      token_type
      strava_scope
      __typename
    }
    nextToken
  }
}