query listAuthsAthletes {
  __typename
  listAuths {
    items {
      id
      access_token
      expires_at
      refresh_token
      strava_scope
      token_type
      __typename
    }
  }
  listAthletes {
    items {
      id
      strava_id
      firstname
      lastname
      profile
      __typename
    }
  }
}