# Generated by Django 4.1 on 2022-09-16 00:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cycletourmap", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tour",
            old_name="tours",
            new_name="activities",
        ),
        migrations.AlterField(
            model_name="activity",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
