# Generated by Django 4.1 on 2022-09-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cycletourmap",
            "0002_rename_tours_tour_activities_alter_activity_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="start_latitude",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="start_longitude",
        ),
    ]
