# Generated by Django 4.1 on 2022-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycletourmap", "0004_alter_activity_end_latlng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="visibility",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
