# Generated by Django 4.1 on 2022-09-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycletourmap", "0005_alter_activity_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="polyline",
            field=models.TextField(blank=True, null=True),
        ),
    ]
