# Generated by Django 4.1 on 2022-09-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycletourmap", "0006_activity_polyline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="gear_id",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
