# Generated by Django 4.1 on 2022-09-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycletourmap", "0007_alter_activity_gear_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="strava_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
