# Generated by Django 4.1 on 2022-09-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycletourmap", "0008_alter_activity_strava_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="upload_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
