# Generated by Django 4.1 on 2023-01-14 00:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cycletourmap", "0009_alter_activity_upload_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity_Detail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "time",
                    models.IntegerField(
                        help_text="Time in seconds since activity start"
                    ),
                ),
                ("distance", models.FloatField()),
                (
                    "latlng",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("altitude", models.IntegerField(blank=True, null=True)),
                ("velocity_smooth", models.FloatField(blank=True, null=True)),
                ("heartrate", models.IntegerField(blank=True, null=True)),
                ("cadence", models.IntegerField(blank=True, null=True)),
                ("watts", models.IntegerField(blank=True, null=True)),
                (
                    "temperature",
                    models.IntegerField(help_text="Temperature in Celcius"),
                ),
                ("moving", models.BooleanField(default=True)),
                ("grade_smooth", models.FloatField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cycletourmap.activity",
                    ),
                ),
            ],
            options={
                "db_table": "activity_detail",
            },
        ),
    ]
