# Generated by Django 4.1 on 2022-09-07 02:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("strava", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stravaauth",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="stravaauth",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="stravaauth",
            name="refresh_token",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="stravaauth",
            name="strava_scope",
            field=models.TextField(null=True),
        ),
    ]
