# Generated by Django 4.1 on 2022-09-16 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("strava", "0002_alter_stravaauth_expires_at_alter_stravaauth_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stravaauth",
            name="access_token",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="stravaauth",
            name="refresh_token",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="stravaauth",
            name="strava_scope",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="stravaauth",
            name="token_type",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="stravaauth",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
