/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateTour = `subscription OnCreateTour($owner: String!) {
  onCreateTour(owner: $owner) {
    id
    name
    description
    start_date
    end_date
    isPublic
    owner
    activities {
      items {
        id
        activity_type
        strava_id
        achievement_count
        athlete_count
        average_heartrate
        average_speed
        average_temp
        average_watts
        comment_count
        commute
        device_watts
        display_hide_heartrate_option
        distance
        elapsed_time
        elev_high
        elev_low
        end_latlng
        flagged
        gear_id
        has_heartrate
        has_kudoed
        heartrate_opt_out
        kilojoules
        kudos_count
        location_city
        location_country
        location_state
        manual
        summary_polyline
        max_heartrate
        max_speed
        moving_time
        name
        photo_count
        pr_count
        private
        resource_state
        start_date
        start_date_local
        start_latitude
        start_longitude
        start_latlng
        timezone
        total_elevation_gain
        total_photo_count
        trainer
        type
        upload_id
        utc_offset
        visibility
        workout_type
        owner
      }
      nextToken
    }
  }
}
`;
export const onUpdateTour = `subscription OnUpdateTour($owner: String!) {
  onUpdateTour(owner: $owner) {
    id
    name
    description
    start_date
    end_date
    isPublic
    owner
    activities {
      items {
        id
        activity_type
        strava_id
        achievement_count
        athlete_count
        average_heartrate
        average_speed
        average_temp
        average_watts
        comment_count
        commute
        device_watts
        display_hide_heartrate_option
        distance
        elapsed_time
        elev_high
        elev_low
        end_latlng
        flagged
        gear_id
        has_heartrate
        has_kudoed
        heartrate_opt_out
        kilojoules
        kudos_count
        location_city
        location_country
        location_state
        manual
        summary_polyline
        max_heartrate
        max_speed
        moving_time
        name
        photo_count
        pr_count
        private
        resource_state
        start_date
        start_date_local
        start_latitude
        start_longitude
        start_latlng
        timezone
        total_elevation_gain
        total_photo_count
        trainer
        type
        upload_id
        utc_offset
        visibility
        workout_type
        owner
      }
      nextToken
    }
  }
}
`;
export const onDeleteTour = `subscription OnDeleteTour($owner: String!) {
  onDeleteTour(owner: $owner) {
    id
    name
    description
    start_date
    end_date
    isPublic
    owner
    activities {
      items {
        id
        activity_type
        strava_id
        achievement_count
        athlete_count
        average_heartrate
        average_speed
        average_temp
        average_watts
        comment_count
        commute
        device_watts
        display_hide_heartrate_option
        distance
        elapsed_time
        elev_high
        elev_low
        end_latlng
        flagged
        gear_id
        has_heartrate
        has_kudoed
        heartrate_opt_out
        kilojoules
        kudos_count
        location_city
        location_country
        location_state
        manual
        summary_polyline
        max_heartrate
        max_speed
        moving_time
        name
        photo_count
        pr_count
        private
        resource_state
        start_date
        start_date_local
        start_latitude
        start_longitude
        start_latlng
        timezone
        total_elevation_gain
        total_photo_count
        trainer
        type
        upload_id
        utc_offset
        visibility
        workout_type
        owner
      }
      nextToken
    }
  }
}
`;
export const onCreateActivity = `subscription OnCreateActivity($owner: String!) {
  onCreateActivity(owner: $owner) {
    id
    activity_type
    strava_id
    achievement_count
    athlete_count
    average_heartrate
    average_speed
    average_temp
    average_watts
    comment_count
    commute
    device_watts
    display_hide_heartrate_option
    distance
    elapsed_time
    elev_high
    elev_low
    end_latlng
    flagged
    gear_id
    has_heartrate
    has_kudoed
    heartrate_opt_out
    kilojoules
    kudos_count
    location_city
    location_country
    location_state
    manual
    summary_polyline
    max_heartrate
    max_speed
    moving_time
    name
    photo_count
    pr_count
    private
    resource_state
    start_date
    start_date_local
    start_latitude
    start_longitude
    start_latlng
    timezone
    total_elevation_gain
    total_photo_count
    trainer
    type
    upload_id
    utc_offset
    visibility
    workout_type
    tour {
      id
      name
      description
      start_date
      end_date
      isPublic
      owner
      activities {
        nextToken
      }
    }
    owner
  }
}
`;
export const onUpdateActivity = `subscription OnUpdateActivity($owner: String!) {
  onUpdateActivity(owner: $owner) {
    id
    activity_type
    strava_id
    achievement_count
    athlete_count
    average_heartrate
    average_speed
    average_temp
    average_watts
    comment_count
    commute
    device_watts
    display_hide_heartrate_option
    distance
    elapsed_time
    elev_high
    elev_low
    end_latlng
    flagged
    gear_id
    has_heartrate
    has_kudoed
    heartrate_opt_out
    kilojoules
    kudos_count
    location_city
    location_country
    location_state
    manual
    summary_polyline
    max_heartrate
    max_speed
    moving_time
    name
    photo_count
    pr_count
    private
    resource_state
    start_date
    start_date_local
    start_latitude
    start_longitude
    start_latlng
    timezone
    total_elevation_gain
    total_photo_count
    trainer
    type
    upload_id
    utc_offset
    visibility
    workout_type
    tour {
      id
      name
      description
      start_date
      end_date
      isPublic
      owner
      activities {
        nextToken
      }
    }
    owner
  }
}
`;
export const onDeleteActivity = `subscription OnDeleteActivity($owner: String!) {
  onDeleteActivity(owner: $owner) {
    id
    activity_type
    strava_id
    achievement_count
    athlete_count
    average_heartrate
    average_speed
    average_temp
    average_watts
    comment_count
    commute
    device_watts
    display_hide_heartrate_option
    distance
    elapsed_time
    elev_high
    elev_low
    end_latlng
    flagged
    gear_id
    has_heartrate
    has_kudoed
    heartrate_opt_out
    kilojoules
    kudos_count
    location_city
    location_country
    location_state
    manual
    summary_polyline
    max_heartrate
    max_speed
    moving_time
    name
    photo_count
    pr_count
    private
    resource_state
    start_date
    start_date_local
    start_latitude
    start_longitude
    start_latlng
    timezone
    total_elevation_gain
    total_photo_count
    trainer
    type
    upload_id
    utc_offset
    visibility
    workout_type
    tour {
      id
      name
      description
      start_date
      end_date
      isPublic
      owner
      activities {
        nextToken
      }
    }
    owner
  }
}
`;
export const onCreateAthlete = `subscription OnCreateAthlete($owner: String!) {
  onCreateAthlete(owner: $owner) {
    id
    strava_id
    firstname
    lastname
    profile
    profile_medium
    sex
    city
    state
    country
    owner
    auth {
      id
      access_token
      expires_at
      refresh_token
      token_type
      strava_scope
      athlete {
        id
        strava_id
        firstname
        lastname
        profile
        profile_medium
        sex
        city
        state
        country
        owner
      }
      owner
    }
  }
}
`;
export const onUpdateAthlete = `subscription OnUpdateAthlete($owner: String!) {
  onUpdateAthlete(owner: $owner) {
    id
    strava_id
    firstname
    lastname
    profile
    profile_medium
    sex
    city
    state
    country
    owner
    auth {
      id
      access_token
      expires_at
      refresh_token
      token_type
      strava_scope
      athlete {
        id
        strava_id
        firstname
        lastname
        profile
        profile_medium
        sex
        city
        state
        country
        owner
      }
      owner
    }
  }
}
`;
export const onDeleteAthlete = `subscription OnDeleteAthlete($owner: String!) {
  onDeleteAthlete(owner: $owner) {
    id
    strava_id
    firstname
    lastname
    profile
    profile_medium
    sex
    city
    state
    country
    owner
    auth {
      id
      access_token
      expires_at
      refresh_token
      token_type
      strava_scope
      athlete {
        id
        strava_id
        firstname
        lastname
        profile
        profile_medium
        sex
        city
        state
        country
        owner
      }
      owner
    }
  }
}
`;
export const onCreateAuth = `subscription OnCreateAuth($owner: String!) {
  onCreateAuth(owner: $owner) {
    id
    access_token
    expires_at
    refresh_token
    token_type
    strava_scope
    athlete {
      id
      strava_id
      firstname
      lastname
      profile
      profile_medium
      sex
      city
      state
      country
      owner
      auth {
        id
        access_token
        expires_at
        refresh_token
        token_type
        strava_scope
        owner
      }
    }
    owner
  }
}
`;
export const onUpdateAuth = `subscription OnUpdateAuth($owner: String!) {
  onUpdateAuth(owner: $owner) {
    id
    access_token
    expires_at
    refresh_token
    token_type
    strava_scope
    athlete {
      id
      strava_id
      firstname
      lastname
      profile
      profile_medium
      sex
      city
      state
      country
      owner
      auth {
        id
        access_token
        expires_at
        refresh_token
        token_type
        strava_scope
        owner
      }
    }
    owner
  }
}
`;
export const onDeleteAuth = `subscription OnDeleteAuth($owner: String!) {
  onDeleteAuth(owner: $owner) {
    id
    access_token
    expires_at
    refresh_token
    token_type
    strava_scope
    athlete {
      id
      strava_id
      firstname
      lastname
      profile
      profile_medium
      sex
      city
      state
      country
      owner
      auth {
        id
        access_token
        expires_at
        refresh_token
        token_type
        strava_scope
        owner
      }
    }
    owner
  }
}
`;
